In [1]:
import numpy as np
import time

In [2]:
# NumPy routines which allocate memory and fill arrays with value
a = np.zeros(4);                print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,));             print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.43422186 0.36313948 0.45252639 0.09688852], a shape = (4,), a data type = float64


In [3]:
# NumPy routines which allocate memory and fill arrays with value but do not accept shape as input argument
a = np.arange(4.);              print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4);          print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.):     a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.82361766 0.98255228 0.08737901 0.04792304], a shape = (4,), a data type = float64


In [4]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([5,4,3,2]);  print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]); print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int32
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


In [14]:
# operations on vectors

a = np.arange(10)
print(a)

print(f"a[2].shape: {a[2].shape} a[2] = {a[2]}, Accessing an element returns a scalar")

print(f"a[-1] = {a[-1]}")

try:
    c = a[15]
    print(c)
except Exception as e:
    print("The error message you'll see is:")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2] = 2, Accessing an element returns a scalar
a[-1] = 9
The error message you'll see is:
index 15 is out of bounds for axis 0 with size 10


In [17]:
# slicing

a = np.arange(10)
print(f"a = {a}")

c = a[2:7:1]; print("a[2:7:1] = ", c)

a = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]


In [25]:
#single vector operations

a = np.array([1, 2, 3, 4])
print(f" a : {a}")

b = -a
print(b)

b = np.sum(a)
print(b)

b = np.mean(a)
print(b)

b = a**2
print(b)

 a : [1 2 3 4]
[-1 -2 -3 -4]
10
2.5
[ 1  4  9 16]


In [26]:
# vector vector element wise operations

a = np.array([1, 2, 3, 4])
b = np.array([-1, -2, -3, -4])
print(f"Binary operators work element wise: {a + b}")

Binary operators work element wise: [0 0 0 0]


In [28]:
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


In [29]:
# scalar vector operations

a = np.array([1, 2, 3, 4])

b = 5 * a
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]


In [30]:
# vector vector dot product

def my_dot(a, b):
    x = 0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

In [31]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(f"my_dot(a, b) = {my_dot(a, b)}")

my_dot(a, b) = 24


In [32]:
np.random.seed(1)

a = np.random.rand(10000000)
b = np.random.rand(10000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print(f"np.dot(a, b) = {c: 4f}")
print(f"Vectorized version duration : {1000*(toc-tic):.4f} ms")

tic = time.time()
c = my_dot(a, b)
toc = time.time()

print(f"my_dot(a, b) = {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms")

del(a);del(b)

np.dot(a, b) =  2501072.581681
Vectorized version duration : 6.2761 ms
my_dot(a, b) = 2501072.5817
loop version duration: 2165.3471 ms


In [33]:
# matrix creation

a = np.zeros((1, 5))
print(f"a shape = {a.shape}, a = {a}")

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]


In [34]:
a = np.zeros((2, 1))
print(f"a shape = {a.shape}, a = {a}")

a shape = (2, 1), a = [[0.]
 [0.]]


In [41]:
a = np.random.random_sample((3, 5))
print(a)

[[0.36607953 0.12254939 0.41590761 0.83186916 0.49357909]
 [0.90762403 0.71371965 0.24246182 0.19614305 0.71120633]
 [0.17314952 0.21576912 0.71609203 0.89638213 0.17019093]]


In [ ]:
a = np.array([[[]], [4, 3], [3, 2]]);
print(a)
print(a.shape)

[[5 4]
 [4 3]
 [3 2]]
(3, 2)


In [49]:
a = np.arange(6).reshape(-1, 2)
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [52]:
print(a[2, 0])
print(a[2])

4
[4 5]


In [56]:
a = np.arange(20).reshape(-1, 5)

In [57]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
